# whitelist
branches:
    only:
        - master
notifications:
  irc:
    channels:
      - "irc.uvt.nl#gitlama"
    template:
      - "%{repository_slug}#%{build_number} %{message} --> %{build_url}"
    skip_join: true
language: python
dist: trusty
python: # I don't really care much about Python 2.7 support anymore for this project
    - "3.4"
#before_install:
#  - sudo apt-get update -qq
#  - sudo apt-get install -y xmldiff
#  - pip install -U setuptools
install:
  - pip install pynlpl
  - pip install kafnafparserpy
  - python setup.py install
script:
  - python naffoliapy/tests/naf2folia.py -v
